### ISSUE TITLE
Move onLoad hook into initialPlot invoke callback and add background color prop

### ISSUE THREAD

**Issue by Jastor11** [rynobax/react-native-plotly#20]
Hey @rynobax  - great work with this package. It fits our team's use case perfectly.

After logging all function calls passed to the Webview component, we've found that our `onMessage` handler never fires. This also means that our `onLoad` handler never fires as well. Are you seeing the same thing, or is this only an issue on our end?

When we moved the `onLoad` hook into the `.then` callback inside the `window.Plotly.newPlot` call, everything worked as expected.

We also wanted to dynamically set the background color of the `.chart` div via props and was wondering if we could expose that as a prop on the Plotly component.

I'd happily submit a PR if you're ok with any of those changes.

Thanks again for your work.

**Comment by rynobax** [comment]
Hey, thanks for bringing this up.  The onLoad issue is definitely an issue with the library that I believe I fixed in #22.  I released an alpha version `3.0.1-0` with those changes.  Could you see if that fixes your issue?

As for changing the background color of the div, do you mind sharing more information about what you want to do that?  Definitely open to making that change if needed, but I would like more context about why.

**Comment by Jastor11** [comment]
The alpha version actually works perfectly. Thanks for sharing that.

We wanted to cover the chart with a transparent cover so that touch effects on the chart are ignored, and to show a temporary spinner while the plot loads. Ended up with a clean workaround and your package worked great. Appreciate all the time you put into it.
