### ISSUE TITLE
Demo example does not run on web.

### ISSUE THREAD

**Issue by jgreenemi** [rynobax/react-native-plotly#32]
Just got started working with this, and have been unable to run the example provided in the README in a freshly-created React Native workspace, initialized with `expo init`.

The error in the console gives the following message:

```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

I notice the expo Snack also exhibits some failure, though appears to be a different trace.

Any thoughts on what's happening here?

**Comment by rynobax** [comment]
The issue seems to be that there is not a web implementation of the WebView component.  [Instead it just renders a View](https://github.com/react-native-community/react-native-webview/blob/master/src/WebView.tsx), which does not support most of the WebView props this library uses.

I haven't thought much about what the behavior of this library should be in web.  For now, you could try something like creating a higher level component that decides whether to use a globally available plotly in web or this library on native.  I can look into building that into the library for the future.

**Comment by jgreenemi** [comment]
Hey, thank you for the fast turnaround! I figured as much - went ahead with switching over to `react-plotly.js` as my use case thus far only applies to web and that came up out of the box. Appreciate your looking into it and hope to see development towards that! Will follow your progress.
